import type { Product } from "@/types";
import { users } from "./users";

function product(
  data: Omit<Product, "status"> & { status?: Product["status"] }
): Product {
  return { ...data, status: data.status ?? data.lifecycleState };
}

export const seedProducts: Product[] = [
  product({
    id: "prod-001",
    partNumber: "ITEM-1001",
    name: "Engine Assembly",
    description:
      "Complete high-bypass turbofan engine assembly for commercial aviation propulsion systems.",
    revision: "C",
    lifecycleState: "Released",
    owner: users[0],
    createdAt: "2024-03-12T09:00:00Z",
    updatedAt: "2026-05-20T14:22:00Z",
    category: "Propulsion",
    type: "Assembly",
    productType: "Mechanical",
    weight: "2,450 kg",
    material: "Titanium / Inconel composite",
    documents: 18,
    bomItems: 142,
    tags: ["engine", "propulsion", "faa-certified"],
    department: "Mechanical Engineering",
  }),
  product({
    id: "prod-002",
    partNumber: "ITEM-1002",
    name: "Battery Module",
    description:
      "Lithium-ion battery module with integrated thermal management for auxiliary power.",
    revision: "B",
    lifecycleState: "In Review",
    owner: users[1],
    createdAt: "2025-06-18T10:15:00Z",
    updatedAt: "2026-05-18T09:45:00Z",
    category: "Power Systems",
    type: "Module",
    productType: "Electrical",
    weight: "48.2 kg",
    documents: 11,
    bomItems: 36,
    tags: ["battery", "electrical", "thermal-mgmt"],
    department: "Electrical Engineering",
  }),
  product({
    id: "prod-003",
    partNumber: "ITEM-1003",
    name: "Hydraulic Pump Housing",
    description:
      "Precision-machined hydraulic pump housing with integrated fluid ports and mounting flanges.",
    revision: "A",
    lifecycleState: "Draft",
    owner: users[3],
    createdAt: "2026-03-10T14:20:00Z",
    updatedAt: "2026-05-22T16:30:00Z",
    category: "Hydraulics",
    type: "Part",
    productType: "Mechanical",
    weight: "2.1 kg",
    material: "Aluminum 7075-T6",
    documents: 4,
    bomItems: 0,
    tags: ["hydraulics", "machined"],
    department: "Manufacturing",
  }),
  product({
    id: "prod-004",
    partNumber: "ITEM-1004",
    name: "Avionics Control Module",
    description:
      "Flight control computer module with redundant processing and ARINC 429 interfaces.",
    revision: "D",
    lifecycleState: "Released",
    owner: users[4],
    createdAt: "2023-11-08T09:00:00Z",
    updatedAt: "2026-04-30T11:15:00Z",
    category: "Avionics",
    type: "Module",
    productType: "Electrical",
    documents: 22,
    bomItems: 38,
    tags: ["avionics", "firmware", "do-178c"],
    department: "Program Management",
  }),
  product({
    id: "prod-005",
    partNumber: "ITEM-1005",
    name: "Fuel Line Connector",
    description:
      "Self-sealing fuel line connector rated for high-pressure aviation fuel systems.",
    revision: "A",
    lifecycleState: "Obsolete",
    owner: users[2],
    createdAt: "2022-08-15T13:45:00Z",
    updatedAt: "2026-01-15T08:30:00Z",
    category: "Fuel System",
    type: "Part",
    productType: "Mechanical",
    weight: "0.34 kg",
    material: "Stainless Steel 316L",
    documents: 6,
    bomItems: 3,
    tags: ["fuel", "connector"],
    department: "Quality Assurance",
  }),
  product({
    id: "prod-006",
    partNumber: "ITEM-1006",
    name: "Wing Spar Cap",
    description:
      "Composite wing spar cap forming the primary structural load path in the wing box.",
    revision: "B",
    lifecycleState: "In Review",
    owner: users[0],
    createdAt: "2025-02-22T07:30:00Z",
    updatedAt: "2026-05-21T15:00:00Z",
    category: "Structures",
    type: "Part",
    productType: "Mechanical",
    weight: "6.8 kg",
    material: "CFRP T800/3900",
    documents: 15,
    bomItems: 0,
    tags: ["composite", "structures"],
    department: "Mechanical Engineering",
  }),
  product({
    id: "prod-007",
    partNumber: "ITEM-1007",
    name: "Environmental Control Unit",
    description:
      "Cabin air conditioning and pressurization control unit with dual-loop redundancy.",
    revision: "C",
    lifecycleState: "Released",
    owner: users[1],
    createdAt: "2024-04-11T11:00:00Z",
    updatedAt: "2026-03-28T10:45:00Z",
    category: "Environmental",
    type: "Assembly",
    productType: "Assembly",
    weight: "12.3 kg",
    documents: 18,
    bomItems: 42,
    tags: ["hvac", "pressurization"],
    department: "Mechanical Engineering",
  }),
  product({
    id: "prod-008",
    partNumber: "ITEM-1008",
    name: "Brake Caliper Assembly",
    description:
      "Carbon-carbon brake caliper assembly for main landing gear wheel braking.",
    revision: "A",
    lifecycleState: "Draft",
    owner: users[3],
    createdAt: "2026-04-20T09:30:00Z",
    updatedAt: "2026-05-24T13:20:00Z",
    category: "Landing Gear",
    type: "Assembly",
    productType: "Mechanical",
    weight: "3.9 kg",
    material: "Titanium Grade 5",
    documents: 3,
    bomItems: 11,
    tags: ["landing-gear", "brakes"],
    department: "Manufacturing",
  }),
  product({
    id: "prod-009",
    partNumber: "ITEM-1009",
    name: "Flight Data Recorder",
    description:
      "Crash-survivable flight data recorder compliant with EUROCAE ED-112A.",
    revision: "B",
    lifecycleState: "Released",
    owner: users[4],
    createdAt: "2024-09-05T08:00:00Z",
    updatedAt: "2026-05-10T16:40:00Z",
    category: "Avionics",
    type: "Module",
    productType: "Electrical",
    documents: 14,
    bomItems: 22,
    tags: ["fdr", "certification"],
    department: "Program Management",
  }),
  product({
    id: "prod-010",
    partNumber: "ITEM-1010",
    name: "Landing Gear Strut",
    description:
      "Main landing gear oleo-pneumatic strut with integrated shimmy damping.",
    revision: "B",
    lifecycleState: "In Review",
    owner: users[1],
    createdAt: "2025-01-14T10:00:00Z",
    updatedAt: "2026-05-19T11:30:00Z",
    category: "Landing Gear",
    type: "Assembly",
    productType: "Mechanical",
    weight: "18.7 kg",
    material: "Ti-6Al-4V",
    documents: 9,
    bomItems: 16,
    tags: ["landing-gear", "strut"],
    department: "Mechanical Engineering",
  }),
  product({
    id: "prod-011",
    partNumber: "ITEM-1011",
    name: "Power Distribution Unit",
    description:
      "Primary aircraft power distribution unit with circuit protection and bus monitoring.",
    revision: "A",
    lifecycleState: "Draft",
    owner: users[1],
    createdAt: "2026-02-28T13:00:00Z",
    updatedAt: "2026-05-23T09:15:00Z",
    category: "Electrical",
    type: "Module",
    productType: "Electrical",
    documents: 5,
    bomItems: 28,
    tags: ["power", "distribution"],
    department: "Electrical Engineering",
  }),
  product({
    id: "prod-012",
    partNumber: "ITEM-1012",
    name: "Turbine Blade Assembly",
    description:
      "High-pressure turbine blade assembly with thermal barrier coating for X200 series.",
    revision: "C",
    lifecycleState: "Released",
    owner: users[0],
    createdAt: "2024-07-20T08:30:00Z",
    updatedAt: "2026-05-17T14:00:00Z",
    category: "Engine Components",
    type: "Assembly",
    productType: "Mechanical",
    weight: "4.2 kg",
    material: "Inconel 718",
    documents: 12,
    bomItems: 24,
    tags: ["turbine", "hot-section"],
    department: "Mechanical Engineering",
  }),
];
